### ISSUE TITLE
Mapping struct with custom name and size results into wrong name and no size at all.

### ISSUE THREAD

**Issue by furio** [go-gorp/gorp#265] opened 2015-06-27 20:04 UTC
Using Sqllite3 / Gorp v1 / Go 1.4.2

Using the code in the example
```
type Post struct {
    // db tag lets you specify the column name if it differs from the struct field
    Id      int64  `db:"post_id"`
    Created int64
    Title   string `db:",size:50"`               // Column size set to 50
    Body    string `db:"article_body,size:1024"` // Set both column name and size
}

    // construct a gorp DbMap
    dbmap := &gorp.DbMap{Db: db, Dialect: gorp.SqliteDialect{}}

    // add a table, setting the table name to 'posts' and
    // specifying that the Id property is an auto incrementing PK
    dbmap.AddTableWithName(Post{}, "posts").SetKeys(true, "Id")

    // create the table. in a production system you'd generally
    // use a migration tool, or create the tables via scripts
    err = dbmap.CreateTablesIfNotExists()
```

Creates a table that as a column name `article_body,size:1024` with size 255

**Comment by qrawl** [comment] 2015-06-29 07:59
I've tested your code, it created me a table with this line:

    CREATE TABLE "posts" ("post_id" integer not null primary key autoincrement, "Created" integer, "Title" varchar(50), "article_body" varchar(1024));

It seems correct to me.

Have you tried `go get -u gopkg.in/gorp.v1`? If so, please check the import in the go file, as it could still be `import "github.com/coopernurse/gorp"`.

**Comment by furio** [comment] 2015-06-29 17:59
the import in my go file is "gopkg.in/gorp.v1". I'll retry

**Comment by cs2dsb** [comment] 2015-06-30 00:50
I have a similar issue. 

I have the struct field 
    Name        string  `db:"name,size:50"`

And when I run
    _, err := dbmap.Select(&items, "select * from item order by name")

I get the error
    gorp: No fields [name] in type Item

If I take the size: tag off it works.

I've tried both gopkg.in/gorp.v1 and github.com/go-gorp/gorp and I've run go get -u to make sure they are up to date.

**Comment by qrawl** [comment] 2015-06-30 07:41
What platform do you experience the problem on? Can you please post the entire minimum compiling code to reproduce the issue? 

[This code](https://gist.github.com/qrawl/a081fdd931c8c6ccd14d) works for me:


![sqlitebrowser screenshot](http://qrawl.net/gorpsizebug.png)

**Comment by GeertJohan** [comment] 2015-06-30 08:03
In MySQL, a varchar can't exceed 255 characters. That might be your problem @furio. 
@cs2dsb you are having a different issue, but please share a compiling example as @qrawl mentioned so we can reproduce.

**Comment by cs2dsb** [comment] 2015-06-30 11:52
I'm experiencing the issue on Windows. I've taken the code @qrawl posted and added a fetch after creating the database and i get the same error I was having "no fields [...] in Post" - the missing fields correspond to those with size: set.

The full code, the log and a screenshot of the database it created are [in this gist](https://gist.github.com/cs2dsb/5a0efee98e1725fd2723)

I've was using postgres when I originally had the issue but this example is using sqllite for ease of sharing.

**Comment by cs2dsb** [comment] 2015-06-30 11:59
@GeertJohan Raised #266 to track my issue as requested

**Comment by GeertJohan** [comment] 2015-06-30 13:11
@cs2dsb Thanks!

@furio I misread, you're using sqlite3, not MySQL. And the table name is also wrong.. This really seems like an old version of gorp.. Is the binary built with the same `gopath` as where you run `go get -u`?

**Comment by GeertJohan** [comment] 2015-06-30 14:02
@furio I know what's going on. v1 doesn't have the size tag at all. It was added to the master branch recently and is scheduled to be released with v2. I wouldn't recommend using the master branch in production or any other software that should be stable. We're going to clean up the codebase and work towards v2 on the master branch. v1 won't change in the meantime.

Sqlite doesn't enforce the size set to varchar(N), according to the docs a varchar(50) could contain 10-milion chars. If you need enforced size, I suggest doing this manually at application level.

I assume this answers your question. If you have any further questions please do no hesitate to re-open this issue again.

**Closed by GeertJohan** 2015-06-30 14:02 UTC
Labels: question

**Comment by furio** [comment] 2015-07-01 20:46
Ah, thank you that explains it. Anyway by using manual binding the correct size is sent, so i'm using that until v2 is out.
