### ISSUE TITLE
Missing for varchar containing % symbol

### ISSUE THREAD

**Issue by kirxcy** [go-gorp/gorp#208] opened 2014-11-03 15:08 UTC
I use a postgres database. I have a table with a varchar(255) column. In one of the row I have the value with % symbol inside.
And using this function:
dbmap.Select(&result, "SELECT * FROM user_item ui JOIN item i ON ui.item_id = i.item_id WHERE user_id = :id AND amount > 0", map[string]interface{}{"id": user_id })
I get %!"(MISSING) in the value (of the particular column)

**Comment by ipartner** [comment] 2015-04-08 23:42
i have the same issue . is there a newer version of gorp with ths fixed?

**Comment by GeertJohan** [comment] 2015-04-09 07:55
@ipartner Not that I am aware of. I haven't bumped into this issue myself yet, could you maybe share example code to reproduce the problem?

**Comment by ipartner** [comment] 2015-04-09 14:56
Sorry looks like in the response to the client i was using fmt.Fprintf(w,bytes) insted of 

w.Write(bytes) directly and the Fprintf saw those %20 and tried to match it to in exsistant parameters so 
if you ask me close the issue

**Comment by qrawl** [comment] 2015-06-30 07:50
Please add a comment here if you experience the problem again. In the meanwhile, I'm closing the issue.

**Closed by qrawl** 2015-06-30 07:50 UTC
